from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from .forms import ConverterForm
from .converter import Number

# Create your views here.
def description(request):
    """
    View which displas text decription of application
    """
    template = loader.get_template("number_converter_app/description.html")
    context = {}
    return HttpResponse(template.render(context, request))


def index(request):
    """
    View which displays main page with userfor for input
    """
    form = ConverterForm()

    template = loader.get_template("number_converter_app/index.html")
    context = {"form": form}
    return HttpResponse(template.render(context, request))


def result(request):
    """
    View which displays all content of index with addidion of result generated by application
    """
    form = ConverterForm()

    template = loader.get_template("number_converter_app/result.html")
    given_number = request.POST.get("given_number")

    MyNumber = Number(given_number)

    context = {
        "form": form,
        "given_number": given_number,
        "result": MyNumber.result,
    }
    return HttpResponse(template.render(context, request))